# Generated by Django 3.2.9 on 2021-12-01 14:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PlantSensors', '0002_alter_measurement_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='sensor_type',
            field=models.CharField(default='Feuchtigkeit', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='measurement',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
