# Generated by Django 3.2.9 on 2021-12-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlantSensors', '0004_auto_20211201_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='type',
            field=models.CharField(default='Temperatur', max_length=20),
            preserve_default=False,
        ),
    ]
